import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ModalProvider } from "@/app/Components/Modal/ModalContext";
import { PlayerProvider } from "./Components/Extras/PlayerContext";
import { FontSizeProvider } from "@/app/Components/Modal/ModalContext";
import PlayerBar from "./Components/Extras/PlayerBar";
import LoginModal from "@/app/Components/Modal/LoginModal";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ModalProvider>
          <FontSizeProvider>
            <PlayerProvider>
              {children}
              <LoginModal />
              <PlayerBar />
            </PlayerProvider>
          </FontSizeProvider>
        </ModalProvider>
      </body>
    </html>
  );
}
